name: Docker Publish

on:
   push:
      branches: ["main"]
   workflow_dispatch: {}

env:
   IMAGE_NAME: typedelta/sharebin

jobs:
   lint:
      uses: ./.github/workflows/lint.yml

   build-and-push:
      name: Build & Push Docker Image
      runs-on: ubuntu-latest
      needs: lint
      permissions:
         contents: read
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4
         - name: Set up QEMU (multi-arch)
           uses: docker/setup-qemu-action@v3
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Log in to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Extract version from package.json
           id: get_version
           run: |
              VERSION=$(node -p "require('./package.json').version")
              echo "Project version: $VERSION"
              echo "version=$VERSION" >> $GITHUB_OUTPUT
         - name: Build and push (multi-arch)
           uses: docker/build-push-action@v6
           with:
              context: .
              push: true
              platforms: linux/amd64,linux/arm64
              tags: |
                 ${{ env.IMAGE_NAME }}:latest
                 ${{ env.IMAGE_NAME }}:alpha-${{ steps.get_version.outputs.version }}
              labels: |
                 org.opencontainers.image.source=${{ github.repository }}
                 org.opencontainers.image.revision=${{ github.sha }}
                 org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
         - name: Summary
           run: |
              echo "Published tags:" >> $GITHUB_STEP_SUMMARY
              echo "- ${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
              echo "- ${{ env.IMAGE_NAME }}:alpha-${{ steps.get_version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
