name: Lint

on:
   workflow_dispatch: {}

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: "22.x"
              cache: "npm"
              cache-dependency-path: |
                 package-lock.json
                 frontend/package-lock.json
                 backend/package.json

         - name: Cache root node_modules
           uses: actions/cache@v4
           with:
              path: node_modules
              key: ${{ runner.os }}-root-${{ hashFiles('package-lock.json', 'package.json') }}
              restore-keys: |
                 ${{ runner.os }}-root-

         - name: Install root dev deps (eslint)
           run: |
              if [ -d node_modules ]; then
                echo "Root node_modules cache hit"; exit 0; fi
              npm i --no-audit --no-fund --only=dev

         - name: Cache frontend node_modules
           uses: actions/cache@v4
           with:
              path: frontend/node_modules
              key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
              restore-keys: |
                 ${{ runner.os }}-frontend-

         - name: Install frontend deps
           working-directory: frontend
           run: |
              if [ -d node_modules ]; then echo "Frontend node_modules cache hit"; exit 0; fi
              if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm i --no-audit --no-fund; fi

         - name: Cache backend node_modules
           uses: actions/cache@v4
           with:
              path: backend/node_modules
              key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json', 'backend/package.json', 'backend/bun.lockb') }}
              restore-keys: |
                 ${{ runner.os }}-backend-

         - name: Install backend deps
           working-directory: backend
           run: |
              if [ -d node_modules ]; then echo "Backend node_modules cache hit"; exit 0; fi
              if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm i --no-audit --no-fund; fi

         - name: Run lint (root aggregator)
           run: npm run lint

         - name: Package versions summary
           run: |
              echo "Root version: $(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
              echo "Frontend version: $(node -p "require('./frontend/package.json').version")" >> $GITHUB_STEP_SUMMARY
